Ants_And_Doodlebugs: Tests2 Class Reference
Tests2 Class Reference
#include <Tests2.h>
Public Member Functions
Tests2 ()
bool doTests ()
bool runProductionTest ()
bool oneDoodlebugStepTest ()
bool oneAntStepTest ()
bool gridTest ()
bool getCellOccupantTest ()
bool setCellOccupantTest ()
bool getCellOccupantPtrTest ()
bool initGridTest ()
bool printGrid ()
bool getOccupantTest ()
bool setOccupantTest ()
bool getOccupantPtrTest ()
bool getRowTest ()
bool getColTest ()
bool getSkipTest ()
bool setSkipTest ()
bool getStepsSinceBreedTest ()
bool targetCellTest ()
bool makeAntsTest ()
bool antsMoveTest ()
bool antsBreedTest ()
bool makeDoodlesTest ()
bool doodleMoveTest ()
bool doodleBreedTest ()
bool doodleEatTest ()
bool getStepsSinceAteTest ()
virtual ~Tests2 ()
Constructor & Destructor Documentation
Tests2()
Tests2::Tests2 ()
Constructs a Test.
~Tests2()
Tests2::~Tests2 () virtual
Destructs a Test.
Referenced by main().
Member Function Documentation
antsBreedTest()
bool Tests2::antsBreedTest ()
Tests that an Ant can breed and produce a new Ant in an adjacent Cell
Returns
true if the test passes; false otherwise
Initial Grid: 0123456789 0 -------— 0 1 -AA-A--— 1 A = Ant 2 –A----— 2 D = Doodlebug 3 -------— 3 - = empty 4 ----—AD- 4 5 ---—AAA- 5 6 ----—A– 6 7 -—A--— 7 8 -------— 8 9 ------—A 9 0123456789
References ant, Ant::breed(), doodlebug, Grid::getCellOccupant(), and Grid::setCellOccupant().
Referenced by doTests().
antsMoveTest()
bool Tests2::antsMoveTest ()
Tests that an Ant can move to an adjacent spot
Returns
true if the test passes; false otherwise
Initial Grid: 0123456789 0 -------— 0 1 -AA-D--— 1 A = Ant 2 –A----— 2 D = Doodlebug 3 -------— 3 - = empty 4 ----—A– 4 5 ---—AAA- 5 6 ----—A– 6 7 -—A--— 7 8 -------— 8 9 ------—A 9 0123456789
References ant, doodlebug, Organism::getCol(), Organism::getRow(), Ant::move(), and Grid::setCellOccupant().
Referenced by doTests().
doodleBreedTest()
bool Tests2::doodleBreedTest ()
Tests that a Doodlebug gives birth to a new Doodlebug in an adjacent Cell
Returns
true if the test passes; false otherwise
Initial Grid: 0123456789 0 -------— 0 1 -AA-D--— 1 A = Ant 2 –A----— 2 D = Doodlebug 3 -------— 3 - = empty 4 ----—AD- 4 5 ---—ADD- 5 6 ----—A– 6 7 -—A--— 7 8 -------— 8 9 ------—D 9 0123456789
References ant, Doodlebug::breed(), doodlebug, Grid::getCellOccupant(), and Grid::setCellOccupant().
Referenced by doTests().
doodleEatTest()
bool Tests2::doodleEatTest ()
Tests that a Doodlebug properly eats
Returns
true if the test passes; false otherwise
References ant, doodlebug, Grid::getCellOccupant(), Production::oneDoodlebugStep(), Grid::setCellOccupant(), and Grid::~Grid().
Referenced by doTests().
doodleMoveTest()
bool Tests2::doodleMoveTest ()
Tests that a Doodlebug can correctly move to an adjacent Dell
Returns
true if the test passes; false otherwise
Initial Grid: 0123456789 0 -------— 0 1 -AA-D--— 1 A = Ant 2 –A----— 2 D = Doodlebug 3 -------— 3 - = empty 4 ----—AD- 4 5 ---—ADD- 5 6 ----—A– 6 7 -—A--— 7 8 -------— 8 9 ------—D 9 0123456789
References ant, doodlebug, Grid::getCellOccupant(), Doodlebug::move(), and Grid::setCellOccupant().
Referenced by doTests().
doTests()
bool Tests2::doTests ()
Performs the tests.
Returns
true if all tests passes; false otherwise
References antsBreedTest(), antsMoveTest(), doodleBreedTest(), doodleEatTest(), doodleMoveTest(), getCellOccupantPtrTest(), getCellOccupantTest(), getColTest(), getOccupantPtrTest(), getOccupantTest(), getRowTest(), getSkipTest(), getStepsSinceAteTest(), getStepsSinceBreedTest(), gridTest(), initGridTest(), makeAntsTest(), makeDoodlesTest(), oneAntStepTest(), oneDoodlebugStepTest(), printGrid(), runProductionTest(), setCellOccupantTest(), setOccupantTest(), setSkipTest(), and targetCellTest().
Referenced by main().
getCellOccupantPtrTest()
bool Tests2::getCellOccupantPtrTest ()
Tests that the function correctly gets the pointer to a Cell.
Returns
true if tests passes; false otherwise
References ant, doodlebug, Grid::getCellOccupantPtr(), Organism::getCol(), Organism::getRow(), Grid::setCellOccupant(), and Grid::~Grid().
Referenced by doTests().
getCellOccupantTest()
bool Tests2::getCellOccupantTest ()
Tests that the function correctly gets the cell occupant type.
Returns
true if tests passes; false otherwise
References ant, doodlebug, empty, Grid::getCellOccupant(), Grid::setCellOccupant(), and Grid::~Grid().
Referenced by doTests().
getColTest()
bool Tests2::getColTest ()
Tests that the function returns the correct column number that an Organism is occupying.
Returns
true if tests passes; false otherwise
References Organism::getCol().
Referenced by doTests().
getOccupantPtrTest()
bool Tests2::getOccupantPtrTest ()
Tests that the function returns the correct pointer to an Organism.
Returns
true if tests passes; false otherwise
References ant, doodlebug, Organism::getCol(), Cell::getOccupantPtr(), Organism::getRow(), Cell::setOccupant(), and Cell::~Cell().
Referenced by doTests().
getOccupantTest()
bool Tests2::getOccupantTest ()
Tests that the function correctly gets the Organism type of a cCll.
Returns
true if tests passes; false otherwise
References ant, doodlebug, empty, Cell::getOccupant(), and Cell::setOccupant().
Referenced by doTests().
getRowTest()
bool Tests2::getRowTest ()
Tests that the function returns the correct row number that the Organism is occupying.
Returns
true if tests passes; false otherwise
References Organism::getRow().
Referenced by doTests().
getSkipTest()
bool Tests2::getSkipTest ()
Tests that the skip variable returns the correct value.
Returns
true if tests passes; false otherwise
References Organism::getSkip(), and Organism::setSkip().
Referenced by doTests().
getStepsSinceAteTest()
bool Tests2::getStepsSinceAteTest ()
Tests that the number of steps since a Doodlebug ate is correct
Returns
true if tests passes; false otherwise
References doodlebug, Doodlebug::getStepsSinceAte(), Production::oneDoodlebugStep(), Grid::setCellOccupant(), Grid::~Grid(), and Production::~Production().
Referenced by doTests().
getStepsSinceBreedTest()
bool Tests2::getStepsSinceBreedTest ()
Tests that the number of steps since an Organism breed is correct.
Returns
true if tests passes; false otherwise
References ant, Organism::getStepsSinceBreed(), Production::oneAntStep(), Grid::setCellOccupant(), Grid::~Grid(), and Production::~Production().
Referenced by doTests().
gridTest()
bool Tests2::gridTest ()
Tests grid initialization and adding organisms.
Returns
true if test passes; false otherwise
References ant, doodlebug, empty, Grid::getCellOccupant(), Grid::setCellOccupant(), and Grid::~Grid().
Referenced by doTests().
initGridTest()
bool Tests2::initGridTest ()
Tests that the Grid is correctly initialized.
Returns
true if tests passes; false otherwise
References empty, Grid::getCellOccupant(), Grid::getCellOccupantPtr(), and Grid::~Grid().
Referenced by doTests().
makeAntsTest()
bool Tests2::makeAntsTest ()
Tests that an Ant can be created
Returns
true if the test passes; false otherwise
References ant, doodlebug, empty, Grid::getCellOccupant(), and Grid::setCellOccupant().
Referenced by doTests().
makeDoodlesTest()
bool Tests2::makeDoodlesTest ()
Tests that a Doodlebug is correctly created
Returns
true if the test passes; false otherwise
References ant, doodlebug, empty, Grid::getCellOccupant(), and Grid::setCellOccupant().
Referenced by doTests().
oneAntStepTest()
bool Tests2::oneAntStepTest ()
Tests that one time step for an Ant can properly be executed.
The board that will be tested:
            -x-
            --x
            xo-
Returns
true if tests passes; false otherwise
References ant, doodlebug, empty, Grid::getCellOccupant(), Production::oneAntStep(), Grid::printGrid(), Grid::setCellOccupant(), Grid::~Grid(), and Production::~Production().
Referenced by doTests().
oneDoodlebugStepTest()
bool Tests2::oneDoodlebugStepTest ()
Tests that one time step for a Doodlebug can properly be executed.
The board that will be tested (but has grid size of 20):
            -x-
            --x
            xo-
Returns
true if tests passes; false otherwise
References ant, doodlebug, empty, Grid::getCellOccupant(), Production::oneDoodlebugStep(), Grid::setCellOccupant(), Grid::~Grid(), and Production::~Production().
Referenced by doTests().
printGrid()
bool Tests2::printGrid ()
Tests that the Grid can be correctly printed.
The Grid created will look like this:
            --xo
            -x-x
            oxox
            o--o
    Where an 'x' is a doodlebug and an 'o' is an ant and '-' is a space
Returns
true if tests passes (must be inspected manually) false otherwise
References ant, doodlebug, Grid::printGrid(), Grid::setCellOccupant(), and Grid::~Grid().
Referenced by doTests().
runProductionTest()
bool Tests2::runProductionTest ()
Tests that the main production method functions properly.
Returns
true if tests passes; false otherwise
References Production::runProduction(), and Production::~Production().
Referenced by doTests().
setCellOccupantTest()
bool Tests2::setCellOccupantTest ()
Tests that the function correctly sets the cell occupant type.
Returns
true if tests passes; false otherwise
References ant, doodlebug, Cell::getOccupant(), Cell::setOccupant(), and Cell::~Cell().
Referenced by doTests().
setOccupantTest()
bool Tests2::setOccupantTest ()
Tests that the function correctly sets the Organism type of a Cell.
Returns
true if tests passes; false otherwise
References ant, doodlebug, Cell::getOccupant(), Cell::setOccupant(), and Cell::~Cell().
Referenced by doTests().
setSkipTest()
bool Tests2::setSkipTest ()
Tests that the skip variable can be set correctly.
Returns
true if tests passes; false otherwise
References Organism::getSkip(), and Organism::setSkip().
Referenced by doTests().
targetCellTest()
bool Tests2::targetCellTest ()
Tests that the function returns the space an Organism should move to. Doodlebugs move to a Cell with an Ant before moving to an empty cell. Ants move to any random Cell. If no empty Cells, the function returns 0.
Returns
true if tests passes; false otherwise
References ant, doodlebug, left, Grid::setCellOccupant(), Organism::targetCell(), up, and Grid::~Grid().
Referenced by doTests().
The documentation for this class was generated from the following files:
Tests2.h
Tests2.cpp