Ants_And_Doodlebugs: Cell Class Reference
Cell Class Reference
#include <Cell.h>
Public Member Functions
Cell ()
occupationStatus getOccupant ()
void setOccupant (occupationStatus g, Organism *o_ptr)
Organism * getOccupantPtr ()
virtual ~Cell ()
Private Attributes
Organism * org
occupationStatus guest
Constructor & Destructor Documentation
Cell()
Cell::Cell ()
Constructs a Cell.
References empty, guest, and org.
~Cell()
Cell::~Cell () virtual
Destructs a Cell.
Referenced by Tests2::getOccupantPtrTest(), Tests2::setCellOccupantTest(), Tests2::setOccupantTest(), and Grid::~Grid().
Member Function Documentation
getOccupant()
occupationStatus Cell::getOccupant ()
Gets whether the cell is occupied by an Ant or Doodlebug, or if it's empty.
Returns
the Ant or Doodlebug in a cell. If not occupied, returns empty
References guest.
Referenced by Grid::getCellOccupant(), Tests2::getOccupantTest(), Tests2::setCellOccupantTest(), and Tests2::setOccupantTest().
getOccupantPtr()
Organism * Cell::getOccupantPtr ()
Gets the pointer in the Cell.
Returns
The pointer to the Cell
References org.
Referenced by Grid::getCellOccupantPtr(), and Tests2::getOccupantPtrTest().
setOccupant()
void Cell::setOccupant (occupationStatus g, Organism * o_ptr)
Sets the occupant of a Cell.
Parameters
g ant, doodlebug, or empty
o_ptr the pointer to an organism or nullptr if empty
References guest, and org.
Referenced by Tests2::getOccupantPtrTest(), Tests2::getOccupantTest(), Grid::initGrid(), Grid::setCellOccupant(), Tests2::setCellOccupantTest(), and Tests2::setOccupantTest().
Field Documentation
guest
occupationStatus Cell::guest private
Referenced by Cell(), getOccupant(), and setOccupant().
org
Organism* Cell::org private
Referenced by Cell(), getOccupantPtr(), and setOccupant().
The documentation for this class was generated from the following files:
Cell.h
Cell.cpp