Ants_And_Doodlebugs: Ant Class Reference
Ant Class Reference
#include <Ant.h>
Public Member Functions
Ant (int r=0, int c=0, bool s=false)
bool move (Grid *g, int n)
bool breed (Grid *g, int n)
virtual ~Ant ()
Public Member Functions inherited from Organism
Organism (int r=0, int c=0, bool s=false)
int getRow ()
int getCol ()
bool getSkip ()
void setSkip (bool s)
int getStepsSinceBreed ()
moveLocation targetCell (Grid *g, int r, int c, int n, bool dMove)
virtual ~Organism ()
Additional Inherited Members
Protected Attributes inherited from Organism
int row
int col
int stepsSinceBreed
bool skip
int origRow
int origCol
Constructor & Destructor Documentation
Ant()
Ant::Ant (int r = 0, int c = 0, bool s = false)
Constructs an Ant and stores the given row and column.
Parameters
r row to place Ant
c column to place Ant
s true if the Ant should be skipped; false otherwise
Referenced by breed().
~Ant()
Ant::~Ant () virtual
Destructs an Ant. Death of Ant occurs when consumed by Doodlebug.
Member Function Documentation
breed()
bool Ant::breed (Grid * g, int n) virtual
Gives birth to an Ant in a randomly chosen empty adjacent cell. Can only give birth after surviving 3 steps. No birth occurs if all adjacent cells are occupied. Can give birth on next step if all adjacent cells are occupied.
Parameters
g The grid with the organisms
n The number of cells on an edge
Returns
true if Ant gave birth; false otherwise
Implements Organism.
References ant, Ant(), Organism::col, down, left, Organism::origCol, Organism::origRow, right, Organism::row, Grid::setCellOccupant(), stay, Organism::stepsSinceBreed, Organism::targetCell(), and up.
Referenced by Tests2::antsBreedTest(), and Production::oneAntStep().
move()
bool Ant::move (Grid * g, int n) virtual
Checks if an adjacent cell is occupied, and if not, randomly selects one and moves to that cell.
Parameters
g The grid with the organisms
n The number of cells on an edge
Returns
true if Ant moved; false otherwise
Implements Organism.
References ant, Organism::col, down, empty, left, Organism::origCol, Organism::origRow, right, Organism::row, Grid::setCellOccupant(), Organism::skip, stay, Organism::stepsSinceBreed, Organism::targetCell(), and up.
Referenced by Tests2::antsMoveTest(), and Production::oneAntStep().
The documentation for this class was generated from the following files:
Ant.h
Ant.cpp