Ants_And_Doodlebugs: Production Class Reference
Production Class Reference
#include <Production.h>
Public Member Functions
Production (int argc, char *argv[])
bool runProduction ()
bool oneDoodlebugStep (Grid *g, int r, int c)
bool oneAntStep (Grid *g, int r, int c)
virtual ~Production ()
Private Attributes
int gridSize
int numDoodlebugs
int numAnts
int numTimeSteps
int seed
int pause
Constructor & Destructor Documentation
Production()
Production::Production (int argc, char * argv[])
Constructs a Production
Parameters
argc Number of arguments on the Command Line
argv Array of arguments on the Command Line
References gridSize, numAnts, numDoodlebugs, numTimeSteps, pause, and seed.
Referenced by main().
~Production()
Production::~Production () virtual
Destructs Production.
Referenced by Tests2::getStepsSinceAteTest(), Tests2::getStepsSinceBreedTest(), main(), Tests2::oneAntStepTest(), Tests2::oneDoodlebugStepTest(), and Tests2::runProductionTest().
Member Function Documentation
oneAntStep()
bool Production::oneAntStep (Grid * g, int r, int c)
Simulates an Ant for one step.
Parameters
g Grid that contains the organisms
r Row of the Ant
c Column of the Ant
Returns
true if birth was given; false otherwise;
References Ant::breed(), Grid::getCellOccupantPtr(), Organism::getStepsSinceBreed(), gridSize, and Ant::move().
Referenced by Tests2::getStepsSinceBreedTest(), Tests2::oneAntStepTest(), and runProduction().
oneDoodlebugStep()
bool Production::oneDoodlebugStep (Grid * g, int r, int c)
Simulates a Doodlebug for one step.
Parameters
g Grid that contains the organisms
r Row of the Doodlebug
c Column of the Doodlebug
Returns
true if birth was given; false otherwise;
References Doodlebug::breed(), empty, Grid::getCellOccupantPtr(), Organism::getCol(), Organism::getRow(), Doodlebug::getStepsSinceAte(), Organism::getStepsSinceBreed(), gridSize, Doodlebug::move(), and Grid::setCellOccupant().
Referenced by Tests2::doodleEatTest(), Tests2::getStepsSinceAteTest(), Tests2::oneDoodlebugStepTest(), and runProduction().
runProduction()
bool Production::runProduction ()
Main Production method.
Returns
true if production seemed to work; false otherwise
We iterate through all of the Cells of the Grid and perform all of
References ant, doodlebug, Grid::getCellOccupant(), Grid::getCellOccupantPtr(), Organism::getSkip(), gridSize, Grid::initGrid(), numAnts, numDoodlebugs, numTimeSteps, oneAntStep(), oneDoodlebugStep(), pause, Grid::printGrid(), seed, and Organism::setSkip().
Referenced by main(), and Tests2::runProductionTest().
Field Documentation
gridSize
int Production::gridSize private
Referenced by oneAntStep(), oneDoodlebugStep(), Production(), and runProduction().
numAnts
int Production::numAnts private
Referenced by Production(), and runProduction().
numDoodlebugs
int Production::numDoodlebugs private
Referenced by Production(), and runProduction().
numTimeSteps
int Production::numTimeSteps private
Referenced by Production(), and runProduction().
pause
int Production::pause private
Referenced by Production(), and runProduction().
seed
int Production::seed private
Referenced by Production(), and runProduction().
The documentation for this class was generated from the following files:
Production.h
Production.cpp