Ants_And_Doodlebugs: Doodlebug Class Reference
Doodlebug Class Reference
#include <Doodlebug.h>
Public Member Functions
Doodlebug (int r=0, int c=0, bool s=false)
int getStepsSinceAte ()
bool move (Grid *g, int n)
bool breed (Grid *g, int n)
bool eat (Grid *g)
virtual ~Doodlebug ()
Public Member Functions inherited from Organism
Organism (int r=0, int c=0, bool s=false)
int getRow ()
int getCol ()
bool getSkip ()
void setSkip (bool s)
int getStepsSinceBreed ()
moveLocation targetCell (Grid *g, int r, int c, int n, bool dMove)
virtual ~Organism ()
Private Attributes
int stepsSinceAte
Additional Inherited Members
Protected Attributes inherited from Organism
int row
int col
int stepsSinceBreed
bool skip
int origRow
int origCol
Constructor & Destructor Documentation
Doodlebug()
Doodlebug::Doodlebug (int r = 0, int c = 0, bool s = false)
Doodlebug Constructor.
Parameters
r Row to initialize Doodlebug
c Column to initialize Doodlebug
s true if the Doodlebug should be skipped; false otherwise
References stepsSinceAte.
Referenced by breed().
~Doodlebug()
Doodlebug::~Doodlebug () virtual
Doodlebug destructor. Death of Doodlebug occurs when Ant not consumed in three steps.
Member Function Documentation
breed()
bool Doodlebug::breed (Grid * g, int n) virtual
Gives birth to a Doodlebug in an adjacent cell. Can only give birth after surviving for eight steps. Doesn't give birth if adjacent cells occupied. Can give birth on next step if all adjacent cells are occupied.
Parameters
g The grid containing the organisms
n The number of cells along an edge of the grid
Returns
true if birth given; false otherwise
Implements Organism.
References Organism::col, doodlebug, Doodlebug(), down, left, Organism::origCol, Organism::origRow, right, Organism::row, Grid::setCellOccupant(), stay, Organism::stepsSinceBreed, Organism::targetCell(), and up.
Referenced by Tests2::doodleBreedTest(), and Production::oneDoodlebugStep().
eat()
bool Doodlebug::eat (Grid * g)
Eats an Ant in an adjacent cell.
Returns
true if Ant eaten; false otherwise
References Organism::col, empty, Grid::getCellOccupant(), Grid::getCellOccupantPtr(), Organism::row, and stepsSinceAte.
Referenced by move().
getStepsSinceAte()
int Doodlebug::getStepsSinceAte ()
Gets number of steps since the Doodlebug ate.
Returns
number of steps since the Doodlebug ate
References stepsSinceAte.
Referenced by Tests2::getStepsSinceAteTest(), and Production::oneDoodlebugStep().
move()
bool Doodlebug::move (Grid * g, int n) virtual
Moves the Doodlebug to an adjacent cell. Does not move if other Doodlebugs are occuping adjacent cells.
Parameters
g The grid containing the organisms
n The number of cells along an edge of the grid
Returns
true if moved; false otherwise
Implements Organism.
References ant, Organism::col, doodlebug, down, eat(), empty, Grid::getCellOccupant(), left, Organism::origCol, Organism::origRow, right, Organism::row, Grid::setCellOccupant(), Organism::skip, stay, stepsSinceAte, Organism::stepsSinceBreed, Organism::targetCell(), and up.
Referenced by Tests2::doodleMoveTest(), and Production::oneDoodlebugStep().
Field Documentation
stepsSinceAte
int Doodlebug::stepsSinceAte private
Referenced by Doodlebug(), eat(), getStepsSinceAte(), and move().
The documentation for this class was generated from the following files:
Doodlebug.h
Doodlebug.cpp