Ants_And_Doodlebugs: Organism Class Reference
Organism Class Reference abstract
#include <Organism.h>
Public Member Functions
Organism (int r=0, int c=0, bool s=false)
int getRow ()
int getCol ()
bool getSkip ()
void setSkip (bool s)
int getStepsSinceBreed ()
virtual bool move (Grid *g, int n)=0
virtual bool breed (Grid *g, int n)=0
moveLocation targetCell (Grid *g, int r, int c, int n, bool dMove)
virtual ~Organism ()
Protected Attributes
int row
int col
int stepsSinceBreed
bool skip
int origRow
int origCol
Constructor & Destructor Documentation
Organism()
Organism::Organism (int r = 0, int c = 0, bool s = false)
Constructs an Organism.
Parameters
r The row of the Organism
c The column of the Organism
s true if the Organism should be skipped; false otherwise
References col, origCol, origRow, row, skip, and stepsSinceBreed.
~Organism()
Organism::~Organism () virtual
Destructs an Organism.
Member Function Documentation
breed()
virtual bool Organism::breed (Grid * g, int n) pure virtual
Implemented in Doodlebug, and Ant.
getCol()
int Organism::getCol ()
Gets the column of an Organism.
Returns
Column of an Organism
References col.
Referenced by Tests2::antsMoveTest(), Tests2::getCellOccupantPtrTest(), Tests2::getColTest(), Tests2::getOccupantPtrTest(), and Production::oneDoodlebugStep().
getRow()
int Organism::getRow ()
Gets the row of an Organism.
Returns
Row of an Organism
References row.
Referenced by Tests2::antsMoveTest(), Tests2::getCellOccupantPtrTest(), Tests2::getOccupantPtrTest(), Tests2::getRowTest(), and Production::oneDoodlebugStep().
getSkip()
bool Organism::getSkip ()
Gets whether an Organism should be skipped in the loop.
Returns
true if Organism should be skipped; false otherwise
References skip.
Referenced by Tests2::getSkipTest(), Production::runProduction(), and Tests2::setSkipTest().
getStepsSinceBreed()
int Organism::getStepsSinceBreed ()
Gets number of steps since an Organism breed.
Returns
number of steps since an Organism breed
References stepsSinceBreed.
Referenced by Tests2::getStepsSinceBreedTest(), Production::oneAntStep(), and Production::oneDoodlebugStep().
move()
virtual bool Organism::move (Grid * g, int n) pure virtual
Implemented in Doodlebug, and Ant.
setSkip()
void Organism::setSkip (bool s)
Sets whether an Organism should be skipped in the loop.
Parameters
s true if an Organism should be skipped; false otherwise
References skip.
Referenced by Tests2::getSkipTest(), Production::runProduction(), and Tests2::setSkipTest().
targetCell()
moveLocation Organism::targetCell (Grid * g, int r, int c, int n, bool dMove)
Determines the spot that an organism should move to or breed in. Determines if the cell above, below, right, and left are occupied, and out of the empty cells, randomly determines the cell to move to or breed in. If the organism is a Doodlebug attempting to move, it will randomly move to an adjacent cell with an Ant in it before moving to an empty cell. Organism does not move if all adjacent cells are filled (unless the Organism is a Doodlebug, and an Ant occupies an adjacent cell).
Parameters
g The grid with the Organisms
r The row of the Organism
c The column of the Organism
n The number of cells on an edge
dMove true if the Organism is a Doodlebug trying to move; false otherwise
Returns
stay if Organism cannot move or breed; up if Organism moves or breeds in cell above; right if Organism moves or breeds in cell to the right; down if Organism moves or breeds in cell below; left if Organism moves or breeds in cell to the left
References ant, down, empty, Grid::getCellOccupant(), left, right, stay, and up.
Referenced by Ant::breed(), Doodlebug::breed(), Ant::move(), Doodlebug::move(), and Tests2::targetCellTest().
Field Documentation
col
int Organism::col protected
Referenced by Ant::breed(), Doodlebug::breed(), Doodlebug::eat(), getCol(), Ant::move(), Doodlebug::move(), and Organism().
origCol
int Organism::origCol protected
Referenced by Ant::breed(), Doodlebug::breed(), Ant::move(), Doodlebug::move(), and Organism().
origRow
int Organism::origRow protected
Referenced by Ant::breed(), Doodlebug::breed(), Ant::move(), Doodlebug::move(), and Organism().
row
int Organism::row protected
Referenced by Ant::breed(), Doodlebug::breed(), Doodlebug::eat(), getRow(), Ant::move(), Doodlebug::move(), and Organism().
skip
bool Organism::skip protected
Referenced by getSkip(), Ant::move(), Doodlebug::move(), Organism(), and setSkip().
stepsSinceBreed
int Organism::stepsSinceBreed protected
Referenced by Ant::breed(), Doodlebug::breed(), getStepsSinceBreed(), Ant::move(), Doodlebug::move(), and Organism().
The documentation for this class was generated from the following files:
Organism.h
Organism.cpp